### ISSUE TITLE
您好！请问为什么我测试30轮，没有看到您的论文解决了内容泄露问题

### ISSUE THREAD

**Issue by Rorschach-xyz** [YingnanMa/RAST#5]
![image](https://user-images.githubusercontent.com/43670613/229495302-e0843d0e-8c00-4b98-8db1-08511795d3bb.png)

**Comment by Rorschach-xyz** [comment]
![image](https://user-images.githubusercontent.com/43670613/229495790-a655bcb9-d1a4-4cb9-9e44-815ac7e05940.png)

**Comment by YingnanMa** [comment]
Hi, compared with the performance of the backbone, RAST framework can improve the content preservation performance. Due to the utilization of multi-restoration, the content information can be preserved well, which can handle the content leak for several sounds. This framework cannot perfectly solve the content leak problem for too many rounds. However, comparing with the backbone, RAST still improves the content preservation performance and handles the content leak problem a lot.

**Comment by YingnanMa** [comment]
issue explained.
